# Generated by Django 5.1.4 on 2025-12-15 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('COURT_HOUR', 'Court per Hour'), ('EQUIPMENT_HOUR', 'Equipment per Hour'), ('COACH_HOUR', 'Coach per Hour')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Base Prices',
                'ordering': ['resource_type'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PEAK_HOUR', 'Peak Hour Surcharge'), ('WEEKEND', 'Weekend Surcharge'), ('INDOOR_COURT', 'Indoor Court Premium')], max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage increase (e.g., 20 for 20%) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_percentage', models.BooleanField(default=True, help_text='If True, value represents a percentage. If False, a fixed amount.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
    ]
