# Generated by Django 5.1.4 on 2025-12-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='description',
            field=models.CharField(blank=True, help_text='User-facing description of the rule', max_length=255),
        ),
    ]
